name: store_manager
description: "Store manager project"
publish_to: "none"
version: 1.0.0+5
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  provider: ^6.1.5
  fl_chart: ^1.0.0
  http: ^1.4.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.1
  flutter_keyboard_visibility: ^6.0.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  intl: ^0.20.2
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
